### ISSUE TITLE
getPrefix call throws an exception

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-plugin-bells#75]
Connector is calling `getPrefix` which throws an exception.

Here's the `plugin-bells` instance when the `getPrefix` is called.
```
FiveBellsLedger {
  _events:
   { '_rpc:notification': [Function],
     incoming_transfer: [Function],
     incoming_prepare: [Function],
     incoming_fulfill: [Function],
     incoming_cancel: [Function],
     incoming_reject: [Function],
     outgoing_transfer: [Function],
     outgoing_prepare: [Function],
     outgoing_fulfill: [Function],
     outgoing_cancel: [Function],
     outgoing_reject: [Function],
     incoming_message: [Function] },
  newListener: false,
  configPrefix: 'us.usd.red.',
  host: null,
  account: 'https://red.ilpdemo.org/ledger/accounts/connie',
  username: undefined,
  identifier: undefined,
  credentials:
   { account: 'https://red.ilpdemo.org/ledger/accounts/connie',
     username: undefined,
     password: '***',
     cert: undefined,
     key: undefined,
     ca: undefined },
  connector: null,
  debugReplyNotifications: false,
  rpcId: 1,
  info: null,
  connection: null,
  connected: false,
  ws: null,
  urls: null }
```  

Here's the exception
```
2016-12-01T01:23:35.760Z connector:app error Error: Prefix has not been set
    at FiveBellsLedger.getPrefix (/var/app/five-bells-wallet/node_modules/ilp-plugin-bells/src/lib/plugin.js:328:29)
    at RouteBroadcaster._crawlClient (/var/app/five-bells-wallet/node_modules/ilp-connector/src/lib/route-broadcaster.js:100:45)
    at next (native)
    at onFulfilled (/var/app/five-bells-wallet/node_modules/co/index.js:65:19)
    at /var/app/five-bells-wallet/node_modules/co/index.js:54:5
    at co (/var/app/five-bells-wallet/node_modules/co/index.js:50:10)
    at toPromise (/var/app/five-bells-wallet/node_modules/co/index.js:118:63)
    at Array.map (native)
    at arrayToPromise (/var/app/five-bells-wallet/node_modules/co/index.js:154:26)
    at toPromise (/var/app/five-bells-wallet/node_modules/co/index.js:120:49)
    at next (/var/app/five-bells-wallet/node_modules/co/index.js:99:29)
    at onFulfilled (/var/app/five-bells-wallet/node_modules/co/index.js:69:7)
    at /var/app/five-bells-wallet/node_modules/co/index.js:54:5
    at co (/var/app/five-bells-wallet/node_modules/co/index.js:50:10)
    at toPromise (/var/app/five-bells-wallet/node_modules/co/index.js:118:63)
    at next (/var/app/five-bells-wallet/node_modules/co/index.js:99:29)
npm run start-prod-connector exited with code 0
```

**Comment by justmoon** [comment]
This is triggered when the connector calls `getPrefix` without telling the plugin to connect first: https://github.com/interledgerjs/ilp-connector/issues/257

We should still change the plugin also so that it prints a better error, like "Must be connected to fetch prefix".

Same goes for most other plugin methods.
